listabusao/lista/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
path('', views.listar, name='menu'),
path('cadastrar/', views.cadastrar, name='cadastrar'),
path('editar/<int:id>', views.editar, name='editar'),
path('lista/(<int:id>)', views.tirar, name='tirar'),
path('nova_lista/', views.novalista, name='novalista'),
]

listabusao/listabusao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lista.urls')),
]

listabusao/lista/models.py
# Create your models here.
from django.db import models

class Aluno(models.Model):
	IDA = 1
	IDAEVOLTA = 2
	VOLTA = 3
	STATUS_CHOICES = (
	    (IDA, 'Ida'),
	    (IDAEVOLTA, 'Ida e volta'),
	    (VOLTA, 'Volta'),
	    
	)


	CADASTRADO = 1
	CARONA = 2
	STATUS_CHOICES2 = (
	    (CADASTRADO, 'Cadastrado'),
	    (CARONA, 'Carona'),
	    
	)
	data = models.DateTimeField(auto_now_add=True) #default = timezone.now
	nome = models.CharField(max_length = 100)
	acao = models.IntegerField(choices=STATUS_CHOICES, default=IDAEVOLTA)
	instituicao = models.CharField(max_length = 10)
	situacao = models.IntegerField(choices=STATUS_CHOICES2, default=CADASTRADO)


	def __str__(self):
		return self.nome

listabusao/lista/forms.py
from django import forms
from .models import Aluno


class AlunoForm(forms.ModelForm):
	class Meta:
		model = Aluno
		fields = ('nome', 'acao', 'instituicao','situacao')
	

listabusao/lista/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Aluno
from .forms import AlunoForm
from datetime import date
from django.utils import timezone
from django.db.models import Count
from django.http import HttpResponse
from datetime import datetime, timedelta
import os
# Create your views here.

def index(request):
    r = requests.get('http://httpbin.org/status/418')
    print(r.text)
    return HttpResponse('<pre>' + r.text + '</pre>')


def listar (request):
	lista0 = Aluno.objects.all().filter(situacao=Aluno.CADASTRADO, acao=Aluno.VOLTA)
	lista1 = Aluno.objects.all().filter(situacao=Aluno.CADASTRADO, acao=Aluno.IDA)

	lista2 = Aluno.objects.all().filter(situacao=Aluno.CARONA,acao=Aluno.VOLTA)
	lista3 = Aluno.objects.all().filter(situacao=Aluno.CARONA,acao=Aluno.IDA)


	return render (request, 'main.html', {"cadastrados": lista0,'caronas': lista2, 'cadastradosi':lista1, 'caronasi':lista3})	

def tirar(request, id):
	aux2=id
	try:
		aux = Aluno.objects.get(id=id)
		aux.delete()
		return redirect('menu')
	except :
		return redirect('menu')


def novalista(request):
	data_e_hora_atuais = datetime.now()
	hora = data_e_hora_atuais.strftime('%H')#o %H retorna apenas a hora
	hora1=int(hora)
	try:
		if hora1 == 19:	
			aux = Aluno.objects.all()
			aux.delete()
			return redirect('menu')
	except :
		return redirect('menu')
	lista0 = Aluno.objects.all().filter(situacao=Aluno.CADASTRADO, acao=Aluno.VOLTA)
	lista1 = Aluno.objects.all().filter(situacao=Aluno.CADASTRADO, acao=Aluno.IDA)

	lista2 = Aluno.objects.all().filter(situacao=Aluno.CARONA,acao=Aluno.VOLTA)
	lista3 = Aluno.objects.all().filter(situacao=Aluno.CARONA,acao=Aluno.IDA)
	return render(request, 'main.html',{'alerta2':'ok', "cadastrados": lista0,'caronas': lista2, 'cadastradosi':lista1, 'caronasi':lista3})
	

def editar(request, id):
	aux = Aluno.objects.get(id=id)
	if request.method=="POST":
		form = AlunoForm(request.POST, instance=aux)
		if form.is_valid():
			aux.save()
			return redirect('menu')
	
	form = AlunoForm(instance=aux)
	return render(request, 'editar.html', {'form':form})

def cadastrar(request):
	if request.method =='POST':
		#formularioReclamacao = Reclamacao(request.POST)
		#if formularioReclamacao.is_valid():
		
		#if nome == 'admin':
		#    return render(request, 'aluno/login.html', {'alerta3': 'Erro'})
		data_atual = date.today()
		data_e_hora_atuais = datetime.now()
		hora = data_e_hora_atuais.strftime('%H')#o %H retorna apenas a hora
		hora1=int(hora)
		
		nome = request.POST['nome']
		acao = request.POST['acao']
		instituicao = request.POST['instituicao']
		situacao = request.POST['situacao']
		
		if 11 <= hora1 < 20:
			lista0 = Aluno.objects.all().filter(situacao=Aluno.CADASTRADO, acao=Aluno.VOLTA)
			lista1 = Aluno.objects.all().filter(situacao=Aluno.CADASTRADO, acao=Aluno.IDA)

			lista2 = Aluno.objects.all().filter(situacao=Aluno.CARONA,acao=Aluno.VOLTA)
			lista3 = Aluno.objects.all().filter(situacao=Aluno.CARONA,acao=Aluno.IDA)
			if acao=='2':
				Aluno.objects.create(nome=nome, acao='1', instituicao=instituicao, situacao='2')
				Aluno.objects.create(nome=nome, acao='3', instituicao=instituicao, situacao='2')
				if situacao=='1':
					return render(request, 'main.html',{'alerta':'ok', "cadastrados": lista0,'caronas': lista2, 'cadastradosi':lista1, 'caronasi':lista3})
				return redirect('menu')

			Aluno.objects.create(nome=nome, acao=acao, instituicao=instituicao, situacao='2')
			if situacao=='1':
				return render(request, 'main.html',{'alerta':'ok', "cadastrados": lista0,'caronas': lista2, 'cadastradosi':lista1, 'caronasi':lista3})
			
			return redirect('menu')


		if acao=='2':
			Aluno.objects.create(nome=nome, acao='1', instituicao=instituicao, situacao=situacao)
			Aluno.objects.create(nome=nome, acao='3', instituicao=instituicao, situacao=situacao)
			return redirect('menu')
			
		Aluno.objects.create(nome=nome, acao=acao, instituicao=instituicao, situacao=situacao)

		return redirect('menu')
	

def cadastrar1(request):
	if request.method=="POST":
		form = AlunoForm(request.POST)
		if form.is_valid():
			
			model = form.save(commit=False)
			model.save()
			
			lista = Aluno.objects.all()
			return render(request, 'main.html', {"todos": lista})

	else:
		form = AlunoForm()
	return render(request, 'main.html', {'form':form})

listabusao/lista/templates/editar.html
<html>
<head>
	<title>Editar</title>
	<meta charset="utf-8">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>

<body style="background-color:  #848484; ">
  <div class="container-fluid">
    
    

    <div class="row">
      
      <div class="mt-5 col-md-6 offset-md-3 col-12 col-sm-6 offset-sm-3 col-lg-4 offset-lg-4">
        <div class="card shadow-lg p-1 mb-5 bg-white rounded">
          
          <div class="card-body">
            <form   method="POST" class="form-group"  >
             {%csrf_token%}
                   
            
              <div class="form-group ">
                <label for="id_nome">Nome</label>
                <input class="form-control"   type="text" name="nome" maxlength="100" required >               
              </div>

              <div class="form-group ">
                <label for="id_nome">Ação</label>
                <select class="form-control" name="acao" >
                  <option value="1" > só ida</option>
                  <option value="2"> Ida e volta</option>
                  <option  value="3">Só volta</option>
                               
                  </select>               
              </div>
              
              <div class="form-group ">
                <label for="id_nome">Instituição</label>
                <select class="form-control" name="instituicao" >
                  <option >IFRN</option>
                  <option >UFRN</option>
                  <option >UERN</option>
                  <option >Outra</option>               
                  </select>               
              </div>
              <div class="form-group ">
                <label for="id_nome">Situação</label>
                <select class="form-control" name="situacao" >
                  <option value="CADASTRADO">Cadastrado</option>
                  <option value="CARONA">Carona</option>
                  
           
                  </select>               
              </div>

                       
            <button  class="btn btn-primary float-right" type="submit" name="button">Confirmar</button>                                       
          </form> 
          </div>
        </div>
      </div>
    </div>

  </div>
</body>

</html>